### ISSUE TITLE
Timing Information

### ISSUE THREAD

**Issue by cloudsftp** [QAR-Lab/uqoclient#1]
The information about the time needed by the D-Wave solver gets discarded.
But it would be very useful to have it included in the Result.

**Comment by QAR-Lab** [comment]
Hello,

We do not discard timing information. You can get the desired information via:


```
answer = Qubo(config, example_qubo).with_platform("dwave").with_solver("INSERT_SOLVER_HERE").solve(1)
timing_info = answer.sampleset.info["timing"])
```
However you raised a good point about the user-experience we overlooked. I will push a update today, which will enable the user to get the timing information via:

```
answer = Qubo(config, example_qubo).with_platform("dwave").with_solver("INSERT_SOLVER_HERE").solve(1)
timing_info = answer.timing
```

Thank you for your great feedback, that helps to make this software better.
Kind Regards,
Sebastian Zielinski
